//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pelicula
    {
        [ScaffoldColumn(false)]
        public int id_pel { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre de la Pelicula es requerida"), MaxLength(55)]
        [Display(Name = "Nombre Pelicula")]
        public string nombre_peli { get; set; }


        [Display(Name = "Fecha de Lanzamiento")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy }")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha_lanzamiento_peli { get; set; }


        [Display(Name = "Categoria")]
        [Required(ErrorMessage = "La categori es requerida es requerida"), MaxLength(55)]
        public string categoria_pel { get; set; }

        [Display(Name = "Duracion")]
        public Nullable<int> duracion_peli { get; set; }
    }
}
